FROM docker.io/library/node:16.10.0-bullseye-slim AS build

WORKDIR /app

COPY package.json yarn.lock ./
COPY packages/backend packages/backend

RUN yarn set version berry && yarn install

WORKDIR /app/packages/backend
RUN yarn build

FROM docker.io/library/node:16.10.0-bullseye-slim

EXPOSE 3000

WORKDIR /app

COPY --from=build /app/package.json /app/yarn.lock ./
COPY --from=build /app/packages/backend/package.json /app/packages/backend/package.json
COPY --from=build /app/packages/backend/dist /app/packages/backend/dist

RUN yarn set version berry && \
    yarn plugin import workspace-tools && \
    yarn workspaces focus --production --all

WORKDIR /app/packages/backend

CMD ["node", "dist/server.js"]
