services:
    jenkins:
        image: jenkins/jenkins:jdk11
        privileged: true
        ports:
            - "8080:8080"
            - "50000:50000"
        container_name: jenkins
        volumes:
            - jenkins_home:/var/jenkins_home
volumes:
    jenkins_home: {}

